"""empty message

Revision ID: e69d918af011
Revises: 8923831406c5
Create Date: 2025-06-12 18:31:11.244484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e69d918af011'
down_revision = '8923831406c5'
branch_labels = None
depends_on = None


def upgrade():
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentences', sa.Column('translated_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sentences', 'translated_text')
    # ### end Alembic commands ###
