// This file is auto-generated by @hey-api/openapi-ts

/**
 * Body_create_project_api_v1_projects__post
 */
export type BodyCreateProjectApiV1ProjectsPost = {
    /**
     * Audio File
     */
    audio_file: Blob | File;
};

/**
 * FootageChoice
 */
export type FootageChoice = {
    /**
     * Sentence Id
     */
    sentence_id: string;
    /**
     * Footage Url
     */
    footage_url: string;
};

/**
 * FootageChoices
 */
export type FootageChoices = {
    /**
     * Footage Choices
     */
    footage_choices: Array<FootageChoice>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MusicRecommendation
 */
export type MusicRecommendation = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Url
     */
    url: string;
};

/**
 * MusicResponse
 */
export type MusicResponse = {
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Recommended Music
     */
    recommended_music: Array<MusicRecommendation>;
};

/**
 * ProjectResponse
 */
export type ProjectResponse = {
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Sentences
     */
    sentences: Array<Sentence>;
};

/**
 * RenderRequest
 */
export type RenderRequest = {
    /**
     * Add Subtitles
     */
    add_subtitles?: boolean;
    /**
     * Include Audio
     */
    include_audio?: boolean;
};

/**
 * RenderResponse
 */
export type RenderResponse = {
    /**
     * Render Task Id
     */
    render_task_id: string;
    /**
     * Status Url
     */
    status_url: string;
};

/**
 * RenderStatusResponse
 */
export type RenderStatusResponse = {
    /**
     * Status
     */
    status: string;
    /**
     * Video Url
     */
    video_url?: string | null;
    /**
     * Error
     */
    error?: string | null;
};

/**
 * SelectedFootage
 */
export type SelectedFootage = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    /**
     * Thumbnail
     */
    thumbnail: string;
    /**
     * Duration
     */
    duration: number;
    /**
     * Tags
     */
    tags: Array<string>;
    /**
     * Category
     */
    category: string;
    /**
     * Mood
     */
    mood: string;
    /**
     * Relevance Score
     */
    relevance_score: number;
    /**
     * Url
     */
    url: string;
};

/**
 * Sentence
 */
export type Sentence = {
    /**
     * Sentence Id
     */
    sentence_id?: string;
    /**
     * Text
     */
    text: string;
    /**
     * Translated Text
     */
    translated_text?: string | null;
    /**
     * Start
     */
    start: number;
    /**
     * End
     */
    end: number;
    /**
     * Recommended Footage Url
     */
    recommended_footage_url?: string | null;
    selected_footage?: SelectedFootage | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type OptionsHandlerFullPathOptionsData = {
    body?: never;
    path: {
        /**
         * Full Path
         */
        full_path: string;
    };
    query?: never;
    url: '/{full_path}';
};

export type OptionsHandlerFullPathOptionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OptionsHandlerFullPathOptionsError = OptionsHandlerFullPathOptionsErrors[keyof OptionsHandlerFullPathOptionsErrors];

export type OptionsHandlerFullPathOptionsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetAllProjectsApiV1ProjectsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/projects/';
};

export type GetAllProjectsApiV1ProjectsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAllProjectsApiV1ProjectsGetError = GetAllProjectsApiV1ProjectsGetErrors[keyof GetAllProjectsApiV1ProjectsGetErrors];

export type GetAllProjectsApiV1ProjectsGetResponses = {
    /**
     * Response Get All Projects Api V1 Projects  Get
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type GetAllProjectsApiV1ProjectsGetResponse = GetAllProjectsApiV1ProjectsGetResponses[keyof GetAllProjectsApiV1ProjectsGetResponses];

export type CreateProjectApiV1ProjectsPostData = {
    body: BodyCreateProjectApiV1ProjectsPost;
    path?: never;
    query?: never;
    url: '/api/v1/projects/';
};

export type CreateProjectApiV1ProjectsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateProjectApiV1ProjectsPostError = CreateProjectApiV1ProjectsPostErrors[keyof CreateProjectApiV1ProjectsPostErrors];

export type CreateProjectApiV1ProjectsPostResponses = {
    /**
     * Successful Response
     */
    200: ProjectResponse;
};

export type CreateProjectApiV1ProjectsPostResponse = CreateProjectApiV1ProjectsPostResponses[keyof CreateProjectApiV1ProjectsPostResponses];

export type DeleteProjectByIdApiV1ProjectsProjectIdDeleteData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}';
};

export type DeleteProjectByIdApiV1ProjectsProjectIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteProjectByIdApiV1ProjectsProjectIdDeleteError = DeleteProjectByIdApiV1ProjectsProjectIdDeleteErrors[keyof DeleteProjectByIdApiV1ProjectsProjectIdDeleteErrors];

export type DeleteProjectByIdApiV1ProjectsProjectIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteProjectByIdApiV1ProjectsProjectIdDeleteResponse = DeleteProjectByIdApiV1ProjectsProjectIdDeleteResponses[keyof DeleteProjectByIdApiV1ProjectsProjectIdDeleteResponses];

export type GetProjectDetailsApiV1ProjectsProjectIdGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}';
};

export type GetProjectDetailsApiV1ProjectsProjectIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProjectDetailsApiV1ProjectsProjectIdGetError = GetProjectDetailsApiV1ProjectsProjectIdGetErrors[keyof GetProjectDetailsApiV1ProjectsProjectIdGetErrors];

export type GetProjectDetailsApiV1ProjectsProjectIdGetResponses = {
    /**
     * Response Get Project Details Api V1 Projects  Project Id  Get
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetProjectDetailsApiV1ProjectsProjectIdGetResponse = GetProjectDetailsApiV1ProjectsProjectIdGetResponses[keyof GetProjectDetailsApiV1ProjectsProjectIdGetResponses];

export type PatchProjectApiV1ProjectsProjectIdPatchData = {
    /**
     * Project Data
     */
    body: {
        [key: string]: unknown;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}';
};

export type PatchProjectApiV1ProjectsProjectIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchProjectApiV1ProjectsProjectIdPatchError = PatchProjectApiV1ProjectsProjectIdPatchErrors[keyof PatchProjectApiV1ProjectsProjectIdPatchErrors];

export type PatchProjectApiV1ProjectsProjectIdPatchResponses = {
    /**
     * Response Patch Project Api V1 Projects  Project Id  Patch
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type PatchProjectApiV1ProjectsProjectIdPatchResponse = PatchProjectApiV1ProjectsProjectIdPatchResponses[keyof PatchProjectApiV1ProjectsProjectIdPatchResponses];

export type UpdateProjectByIdApiV1ProjectsProjectIdPutData = {
    /**
     * Project Data
     */
    body: {
        [key: string]: unknown;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}';
};

export type UpdateProjectByIdApiV1ProjectsProjectIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateProjectByIdApiV1ProjectsProjectIdPutError = UpdateProjectByIdApiV1ProjectsProjectIdPutErrors[keyof UpdateProjectByIdApiV1ProjectsProjectIdPutErrors];

export type UpdateProjectByIdApiV1ProjectsProjectIdPutResponses = {
    /**
     * Response Update Project By Id Api V1 Projects  Project Id  Put
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type UpdateProjectByIdApiV1ProjectsProjectIdPutResponse = UpdateProjectByIdApiV1ProjectsProjectIdPutResponses[keyof UpdateProjectByIdApiV1ProjectsProjectIdPutResponses];

export type SubmitFootageChoicesApiV1ProjectsProjectIdFootagePostData = {
    body: FootageChoices;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/footage';
};

export type SubmitFootageChoicesApiV1ProjectsProjectIdFootagePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubmitFootageChoicesApiV1ProjectsProjectIdFootagePostError = SubmitFootageChoicesApiV1ProjectsProjectIdFootagePostErrors[keyof SubmitFootageChoicesApiV1ProjectsProjectIdFootagePostErrors];

export type SubmitFootageChoicesApiV1ProjectsProjectIdFootagePostResponses = {
    /**
     * Successful Response
     */
    200: MusicResponse;
};

export type SubmitFootageChoicesApiV1ProjectsProjectIdFootagePostResponse = SubmitFootageChoicesApiV1ProjectsProjectIdFootagePostResponses[keyof SubmitFootageChoicesApiV1ProjectsProjectIdFootagePostResponses];

export type RenderProjectApiV1ProjectsProjectIdRenderPostData = {
    body: RenderRequest;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/render';
};

export type RenderProjectApiV1ProjectsProjectIdRenderPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RenderProjectApiV1ProjectsProjectIdRenderPostError = RenderProjectApiV1ProjectsProjectIdRenderPostErrors[keyof RenderProjectApiV1ProjectsProjectIdRenderPostErrors];

export type RenderProjectApiV1ProjectsProjectIdRenderPostResponses = {
    /**
     * Successful Response
     */
    202: RenderResponse;
};

export type RenderProjectApiV1ProjectsProjectIdRenderPostResponse = RenderProjectApiV1ProjectsProjectIdRenderPostResponses[keyof RenderProjectApiV1ProjectsProjectIdRenderPostResponses];

export type GetRenderStatusApiV1ProjectsRenderStatusRenderTaskIdGetData = {
    body?: never;
    path: {
        /**
         * Render Task Id
         */
        render_task_id: string;
    };
    query?: never;
    url: '/api/v1/projects/render/status/{render_task_id}';
};

export type GetRenderStatusApiV1ProjectsRenderStatusRenderTaskIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRenderStatusApiV1ProjectsRenderStatusRenderTaskIdGetError = GetRenderStatusApiV1ProjectsRenderStatusRenderTaskIdGetErrors[keyof GetRenderStatusApiV1ProjectsRenderStatusRenderTaskIdGetErrors];

export type GetRenderStatusApiV1ProjectsRenderStatusRenderTaskIdGetResponses = {
    /**
     * Successful Response
     */
    200: RenderStatusResponse;
};

export type GetRenderStatusApiV1ProjectsRenderStatusRenderTaskIdGetResponse = GetRenderStatusApiV1ProjectsRenderStatusRenderTaskIdGetResponses[keyof GetRenderStatusApiV1ProjectsRenderStatusRenderTaskIdGetResponses];

export type ClientOptions = {
    baseURL: `${string}://openapi.json` | (string & {});
};