// This file is auto-generated by @hey-api/openapi-ts

/**
 * Body_create_project_api_v1_projects__post
 */
export type BodyCreateProjectApiV1ProjectsPost = {
    /**
     * Audio File
     */
    audio_file: Blob | File;
};

/**
 * FootageChoice
 * Legacy footage choice schema.
 */
export type FootageChoice = {
    /**
     * Sentence Id
     */
    sentence_id: string;
    /**
     * Footage Url
     */
    footage_url: string;
};

/**
 * FootageChoices
 * Legacy footage choices collection.
 */
export type FootageChoices = {
    /**
     * Footage Choices
     */
    footage_choices: Array<FootageChoice>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MusicRecommendation
 * Legacy music recommendation schema.
 */
export type MusicRecommendation = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Url
     */
    url: string;
};

/**
 * MusicResponse
 * Music recommendation response.
 */
export type MusicResponse = {
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Recommended Music
     */
    recommended_music: Array<MusicRecommendation>;
};

/**
 * RenderRequest
 * Schema for video render requests.
 */
export type RenderRequest = {
    /**
     * Add Subtitles
     */
    add_subtitles?: boolean;
    /**
     * Include Audio
     */
    include_audio?: boolean;
};

/**
 * RenderResponse
 * Response schema for render requests.
 */
export type RenderResponse = {
    /**
     * Render Task Id
     */
    render_task_id: string;
    /**
     * Status Url
     */
    status_url: string;
};

/**
 * RenderStatusResponse
 * Response schema for render status queries.
 */
export type RenderStatusResponse = {
    /**
     * Status
     */
    status: string;
    /**
     * Video Url
     */
    video_url?: string | null;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Progress
     */
    progress?: number | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type OptionsHandlerFullPathOptionsData = {
    body?: never;
    path: {
        /**
         * Full Path
         */
        full_path: string;
    };
    query?: never;
    url: '/{full_path}';
};

export type OptionsHandlerFullPathOptionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OptionsHandlerFullPathOptionsError = OptionsHandlerFullPathOptionsErrors[keyof OptionsHandlerFullPathOptionsErrors];

export type OptionsHandlerFullPathOptionsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetAllProjectsApiV1ProjectsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/projects/';
};

export type GetAllProjectsApiV1ProjectsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAllProjectsApiV1ProjectsGetError = GetAllProjectsApiV1ProjectsGetErrors[keyof GetAllProjectsApiV1ProjectsGetErrors];

export type GetAllProjectsApiV1ProjectsGetResponses = {
    /**
     * Response Get All Projects Api V1 Projects  Get
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type GetAllProjectsApiV1ProjectsGetResponse = GetAllProjectsApiV1ProjectsGetResponses[keyof GetAllProjectsApiV1ProjectsGetResponses];

export type CreateProjectApiV1ProjectsPostData = {
    body: BodyCreateProjectApiV1ProjectsPost;
    path?: never;
    query?: never;
    url: '/api/v1/projects/';
};

export type CreateProjectApiV1ProjectsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateProjectApiV1ProjectsPostError = CreateProjectApiV1ProjectsPostErrors[keyof CreateProjectApiV1ProjectsPostErrors];

export type CreateProjectApiV1ProjectsPostResponses = {
    /**
     * Response Create Project Api V1 Projects  Post
     * Successful Response
     */
    201: {
        [key: string]: unknown;
    };
};

export type CreateProjectApiV1ProjectsPostResponse = CreateProjectApiV1ProjectsPostResponses[keyof CreateProjectApiV1ProjectsPostResponses];

export type DeleteProjectApiV1ProjectsProjectIdDeleteData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}';
};

export type DeleteProjectApiV1ProjectsProjectIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteProjectApiV1ProjectsProjectIdDeleteError = DeleteProjectApiV1ProjectsProjectIdDeleteErrors[keyof DeleteProjectApiV1ProjectsProjectIdDeleteErrors];

export type DeleteProjectApiV1ProjectsProjectIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteProjectApiV1ProjectsProjectIdDeleteResponse = DeleteProjectApiV1ProjectsProjectIdDeleteResponses[keyof DeleteProjectApiV1ProjectsProjectIdDeleteResponses];

export type GetProjectDetailsApiV1ProjectsProjectIdGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}';
};

export type GetProjectDetailsApiV1ProjectsProjectIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProjectDetailsApiV1ProjectsProjectIdGetError = GetProjectDetailsApiV1ProjectsProjectIdGetErrors[keyof GetProjectDetailsApiV1ProjectsProjectIdGetErrors];

export type GetProjectDetailsApiV1ProjectsProjectIdGetResponses = {
    /**
     * Response Get Project Details Api V1 Projects  Project Id  Get
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetProjectDetailsApiV1ProjectsProjectIdGetResponse = GetProjectDetailsApiV1ProjectsProjectIdGetResponses[keyof GetProjectDetailsApiV1ProjectsProjectIdGetResponses];

export type PatchProjectApiV1ProjectsProjectIdPatchData = {
    /**
     * Project Data
     */
    body: {
        [key: string]: unknown;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}';
};

export type PatchProjectApiV1ProjectsProjectIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchProjectApiV1ProjectsProjectIdPatchError = PatchProjectApiV1ProjectsProjectIdPatchErrors[keyof PatchProjectApiV1ProjectsProjectIdPatchErrors];

export type PatchProjectApiV1ProjectsProjectIdPatchResponses = {
    /**
     * Response Patch Project Api V1 Projects  Project Id  Patch
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type PatchProjectApiV1ProjectsProjectIdPatchResponse = PatchProjectApiV1ProjectsProjectIdPatchResponses[keyof PatchProjectApiV1ProjectsProjectIdPatchResponses];

export type UpdateProjectApiV1ProjectsProjectIdPutData = {
    /**
     * Project Data
     */
    body: {
        [key: string]: unknown;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}';
};

export type UpdateProjectApiV1ProjectsProjectIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateProjectApiV1ProjectsProjectIdPutError = UpdateProjectApiV1ProjectsProjectIdPutErrors[keyof UpdateProjectApiV1ProjectsProjectIdPutErrors];

export type UpdateProjectApiV1ProjectsProjectIdPutResponses = {
    /**
     * Response Update Project Api V1 Projects  Project Id  Put
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type UpdateProjectApiV1ProjectsProjectIdPutResponse = UpdateProjectApiV1ProjectsProjectIdPutResponses[keyof UpdateProjectApiV1ProjectsProjectIdPutResponses];

export type SubmitFootageChoicesApiV1ProjectsProjectIdFootagePostData = {
    body: FootageChoices;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/footage';
};

export type SubmitFootageChoicesApiV1ProjectsProjectIdFootagePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubmitFootageChoicesApiV1ProjectsProjectIdFootagePostError = SubmitFootageChoicesApiV1ProjectsProjectIdFootagePostErrors[keyof SubmitFootageChoicesApiV1ProjectsProjectIdFootagePostErrors];

export type SubmitFootageChoicesApiV1ProjectsProjectIdFootagePostResponses = {
    /**
     * Successful Response
     */
    200: MusicResponse;
};

export type SubmitFootageChoicesApiV1ProjectsProjectIdFootagePostResponse = SubmitFootageChoicesApiV1ProjectsProjectIdFootagePostResponses[keyof SubmitFootageChoicesApiV1ProjectsProjectIdFootagePostResponses];

export type RenderProjectApiV1ProjectsProjectIdRenderPostData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/render';
};

export type RenderProjectApiV1ProjectsProjectIdRenderPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RenderProjectApiV1ProjectsProjectIdRenderPostError = RenderProjectApiV1ProjectsProjectIdRenderPostErrors[keyof RenderProjectApiV1ProjectsProjectIdRenderPostErrors];

export type RenderProjectApiV1ProjectsProjectIdRenderPostResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};

export type GetProjectRenderStatusApiV1ProjectsRenderStatusTaskIdGetData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/v1/projects/render/status/{task_id}';
};

export type GetProjectRenderStatusApiV1ProjectsRenderStatusTaskIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProjectRenderStatusApiV1ProjectsRenderStatusTaskIdGetError = GetProjectRenderStatusApiV1ProjectsRenderStatusTaskIdGetErrors[keyof GetProjectRenderStatusApiV1ProjectsRenderStatusTaskIdGetErrors];

export type GetProjectRenderStatusApiV1ProjectsRenderStatusTaskIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RenderProjectApiV1RenderProjectIdRenderPostData = {
    body: RenderRequest;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/render/{project_id}/render';
};

export type RenderProjectApiV1RenderProjectIdRenderPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RenderProjectApiV1RenderProjectIdRenderPostError = RenderProjectApiV1RenderProjectIdRenderPostErrors[keyof RenderProjectApiV1RenderProjectIdRenderPostErrors];

export type RenderProjectApiV1RenderProjectIdRenderPostResponses = {
    /**
     * Successful Response
     */
    202: RenderResponse;
};

export type RenderProjectApiV1RenderProjectIdRenderPostResponse = RenderProjectApiV1RenderProjectIdRenderPostResponses[keyof RenderProjectApiV1RenderProjectIdRenderPostResponses];

export type GetRenderStatusApiV1RenderStatusTaskIdGetData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/v1/render/status/{task_id}';
};

export type GetRenderStatusApiV1RenderStatusTaskIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRenderStatusApiV1RenderStatusTaskIdGetError = GetRenderStatusApiV1RenderStatusTaskIdGetErrors[keyof GetRenderStatusApiV1RenderStatusTaskIdGetErrors];

export type GetRenderStatusApiV1RenderStatusTaskIdGetResponses = {
    /**
     * Successful Response
     */
    200: RenderStatusResponse;
};

export type GetRenderStatusApiV1RenderStatusTaskIdGetResponse = GetRenderStatusApiV1RenderStatusTaskIdGetResponses[keyof GetRenderStatusApiV1RenderStatusTaskIdGetResponses];

export type UpdateRenderStatusApiV1RenderStatusTaskIdPutData = {
    /**
     * Status Update
     */
    body: {
        [key: string]: unknown;
    };
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/v1/render/status/{task_id}';
};

export type UpdateRenderStatusApiV1RenderStatusTaskIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateRenderStatusApiV1RenderStatusTaskIdPutError = UpdateRenderStatusApiV1RenderStatusTaskIdPutErrors[keyof UpdateRenderStatusApiV1RenderStatusTaskIdPutErrors];

export type UpdateRenderStatusApiV1RenderStatusTaskIdPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetProjectRenderTasksApiV1RenderProjectIdTasksGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/render/{project_id}/tasks';
};

export type GetProjectRenderTasksApiV1RenderProjectIdTasksGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProjectRenderTasksApiV1RenderProjectIdTasksGetError = GetProjectRenderTasksApiV1RenderProjectIdTasksGetErrors[keyof GetProjectRenderTasksApiV1RenderProjectIdTasksGetErrors];

export type GetProjectRenderTasksApiV1RenderProjectIdTasksGetResponses = {
    /**
     * Response Get Project Render Tasks Api V1 Render  Project Id  Tasks Get
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetProjectRenderTasksApiV1RenderProjectIdTasksGetResponse = GetProjectRenderTasksApiV1RenderProjectIdTasksGetResponses[keyof GetProjectRenderTasksApiV1RenderProjectIdTasksGetResponses];

export type ClientOptions = {
    baseURL: `${string}://openapi.json` | (string & {});
};