version: '3'

services:
  frontend:
    build:
      context: ../
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
      - NODE_ENV=development
    volumes:
      - ../frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ../
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - AI_API_KEY=${AI_API_KEY}
      - ENVIRONMENT=development
    volumes:
      - ../backend:/app
    restart: unless-stopped 