"""add audio_file_path to project model

Revision ID: 8923831406c5
Revises: 48e4ea81bf4b
Create Date: 2025-06-10 21:33:24.168533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8923831406c5'
down_revision = '48e4ea81bf4b'
branch_labels = None
depends_on = None


def upgrade():
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('audio_file_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'audio_file_path')
    # ### end Alembic commands ###
